version: '3.1'

services:
    db:
        image: mysql:8
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge